# Generated by Django 5.2.12 on 2026-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='productdocument',
            options={'ordering': ['sort_order'], 'verbose_name': 'Product Document'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Product Image'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['sort_order'], 'verbose_name': 'Product Specification'},
        ),
        migrations.AlterModelOptions(
            name='relatedproduct',
            options={'ordering': ['sort_order'], 'verbose_name': 'Related Product'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='certification_doc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='datasheet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_configurable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manual',
        ),
        migrations.AddField(
            model_name='product',
            name='dim_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Chiều cao (mm)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dim_length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Chiều dài (mm)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dim_width',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Chiều rộng (mm)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách tính năng nổi bật. Ví dụ: ["IP67", "RS485", "0-10V output"]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, help_text='Số lượng đặt hàng tối thiểu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='Mã linh kiện của nhà sản xuất', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, help_text='Giá niêm yết (VND)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Giá cố định'), ('quote', 'Yêu cầu báo giá'), ('contact', 'Liên hệ để biết giá')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_quote',
            field=models.BooleanField(default=False, help_text='Bắt buộc yêu cầu báo giá, không cho thêm giỏ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Giá khuyến mãi (VND) — để trống nếu không có', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Mã sản phẩm duy nhất', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'Còn hàng'), ('low_stock', 'Sắp hết'), ('out_of_stock', 'Hết hàng'), ('pre_order', 'Đặt trước')], db_index=True, default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Khối lượng (kg)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='doc_type',
            field=models.CharField(choices=[('datasheet', 'Datasheet'), ('manual', 'Hướng dẫn sử dụng'), ('certification', 'Chứng nhận / Certificate'), ('drawing', 'Bản vẽ kích thước'), ('software', 'Phần mềm / Driver'), ('other', 'Tài liệu khác')], default='datasheet', max_length=30),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Kích thước file (bytes)', null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group',
            field=models.CharField(blank=True, help_text='Nhóm thông số (Thông số điện, Kết nối, Môi trường...)', max_length=100),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(help_text='Tên thông số (Điện áp, Dải đo...)', max_length=200),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='unit',
            field=models.CharField(blank=True, help_text='Đơn vị (V, A, °C, mm...)', max_length=50),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(help_text='Giá trị', max_length=500),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='relation_type',
            field=models.CharField(choices=[('accessory', 'Phụ kiện'), ('alternative', 'Sản phẩm thay thế'), ('compatible', 'Tương thích'), ('bundle', 'Bán kèm')], default='compatible', max_length=30),
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
