# Generated by Django 5.2.14 on 2026-05-29 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_brand_options_alter_category_options_and_more'),
        ('products', '0002_remove_product_tags_alter_productdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productdocument',
            options={'ordering': ['sort_order'], 'verbose_name': 'Tài liệu sản phẩm', 'verbose_name_plural': 'Tài liệu sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Ảnh sản phẩm', 'verbose_name_plural': 'Ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['sort_order'], 'verbose_name': 'Thông số kỹ thuật', 'verbose_name_plural': 'Thông số kỹ thuật'},
        ),
        migrations.AlterModelOptions(
            name='relatedproduct',
            options={'ordering': ['sort_order'], 'verbose_name': 'Sản phẩm liên quan', 'verbose_name_plural': 'Sản phẩm liên quan'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.brand', verbose_name='Thương hiệu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dim_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Chiều cao (mm)', max_digits=8, null=True, verbose_name='Chiều cao (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dim_length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Chiều dài (mm)', max_digits=8, null=True, verbose_name='Chiều dài (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dim_width',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Chiều rộng (mm)', max_digits=8, null=True, verbose_name='Chiều rộng (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách tính năng nổi bật. Ví dụ: ["IP67", "RS485", "0-10V output"]', verbose_name='Tính năng nổi bật'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đánh dấu Bán chạy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đánh dấu Mới'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, help_text='Số lượng đặt hàng tối thiểu', verbose_name='SL đặt hàng tối thiểu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='Mã linh kiện của nhà sản xuất', max_length=100, verbose_name='Mã linh kiện'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, help_text='Giá niêm yết (VND)', max_digits=15, null=True, verbose_name='Giá niêm yết'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Giá cố định'), ('quote', 'Yêu cầu báo giá'), ('contact', 'Liên hệ để biết giá')], default='fixed', max_length=20, verbose_name='Loại giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quote_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt báo giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_quote',
            field=models.BooleanField(default=False, help_text='Bắt buộc yêu cầu báo giá, không cho thêm giỏ', verbose_name='Bắt buộc báo giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Giá khuyến mãi (VND) — để trống nếu không có', max_digits=15, null=True, verbose_name='Giá khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Mã sản phẩm duy nhất', max_length=100, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng tồn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'Còn hàng'), ('low_stock', 'Sắp hết'), ('out_of_stock', 'Hết hàng'), ('pre_order', 'Đặt trước')], db_index=True, default='in_stock', max_length=20, verbose_name='Tình trạng kho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Khối lượng (kg)', max_digits=8, null=True, verbose_name='Khối lượng (kg)'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='doc_type',
            field=models.CharField(choices=[('datasheet', 'Datasheet'), ('manual', 'Hướng dẫn sử dụng'), ('certification', 'Chứng nhận / Certificate'), ('drawing', 'Bản vẽ kích thước'), ('software', 'Phần mềm / Driver'), ('other', 'Tài liệu khác')], default='datasheet', max_length=30, verbose_name='Loại tài liệu'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(upload_to='products/documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Kích thước file (bytes)', null=True, verbose_name='Kích thước file'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Ảnh chính'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group',
            field=models.CharField(blank=True, help_text='Nhóm thông số (Thông số điện, Kết nối, Môi trường...)', max_length=100, verbose_name='Nhóm thông số'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(help_text='Tên thông số (Điện áp, Dải đo...)', max_length=200, verbose_name='Tên thông số'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='unit',
            field=models.CharField(blank=True, help_text='Đơn vị (V, A, °C, mm...)', max_length=50, verbose_name='Đơn vị'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(help_text='Giá trị', max_length=500, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='products.product', verbose_name='Sản phẩm liên quan'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='relation_type',
            field=models.CharField(choices=[('accessory', 'Phụ kiện'), ('alternative', 'Sản phẩm thay thế'), ('compatible', 'Tương thích'), ('bundle', 'Bán kèm')], default='compatible', max_length=30, verbose_name='Loại liên kết'),
        ),
    ]
