# Generated by Django 5.2.12 on 2026-04-15 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_phone_number_order_phone'),
        ('solutions', '0002_alter_architectureblock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item'},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quote Request', 'verbose_name_plural': 'Quote Requests'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='country',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='timeline',
        ),
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, help_text='Mã PO của khách hàng (nếu có)', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đã giao vận'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã huỷ'), ('refunded', 'Đã hoàn tiền')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='application',
            field=models.CharField(blank=True, help_text='Ứng dụng / ngành hàng cụ thể', max_length=200),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='solutions.solution'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('in_review', 'Đang xem xét'), ('quoted', 'Đã báo giá'), ('accepted', 'Đã chấp nhận'), ('declined', 'Từ chối')], db_index=True, default='new', max_length=20),
        ),
    ]
