# Generated by Django 5.2.14 on 2026-05-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_options_alter_quoterequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Dòng đơn hàng', 'verbose_name_plural': 'Dòng đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu báo giá', 'verbose_name_plural': 'Yêu cầu báo giá'},
        ),
        migrations.AlterModelOptions(
            name='quoterequestitem',
            options={'verbose_name': 'Dòng báo giá', 'verbose_name_plural': 'Dòng báo giá'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('purchase', 'Đơn mua hàng'), ('quote', 'Yêu cầu báo giá')], default='purchase', max_length=20),
        ),
    ]
