# Generated by Django 5.2.12 on 2026-04-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='in_active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_currency',
            field=models.CharField(default='VND', max_length=3),
        ),
    ]
