# Generated by Django 5.2.12 on 2026-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_in_active_customer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferred_currency',
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_type',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Nhà sản xuất'), ('integrator', 'System Integrator'), ('distributor', 'Nhà phân phối'), ('end_user', 'End User'), ('other', 'Khác')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='Việt Nam', max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(default='Văn phòng', help_text='Ví dụ: "Văn phòng", "Kho hàng"', max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
