# Generated by Django 5.2.12 on 2026-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Ngưỡng cảnh báo sắp hết hàng cho sản phẩm thuộc category này'),
        ),
    ]
