# Generated by Django 5.2.12 on 2026-04-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_requests', to='solutions.solution'),
        ),
    ]
