# Generated by Django 5.2.12 on 2026-04-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_code',
        ),
    ]
