# Generated by Django 5.2.13 on 2026-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cart_coupon_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
