# Generated by Django 5.2.12 on 2026-04-15 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('products', '0002_remove_product_tags_alter_productdocument_options_and_more'),
        ('solutions', '0002_alter_architectureblock_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Nội dung HTML đầy đủ (dùng CKEditor)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'Bài viết kỹ thuật'), ('news', 'Tin tức'), ('case_study', 'Case Study'), ('guide', 'Hướng dẫn')], default='article', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(default=5, help_text='Thời gian đọc ước tính (phút)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='products.product'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_solutions',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='solutions.solution'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags phân cách bởi dấu phẩy. Ví dụ: PLC, IoT, Cảm biến', max_length=500),
        ),
    ]
