# Generated by Django 5.2.12 on 2026-04-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='solutions/categories/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Solution Category',
                'verbose_name_plural': 'Solution Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if needed')),
                ('og_image', models.ImageField(blank=True, help_text='OpenGraph image (1200x630px)', null=True, upload_to='seo/og/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(upload_to='solutions/thumbnails/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='solutions/hero/')),
                ('hero_video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL')),
                ('short_description', models.TextField(max_length=500)),
                ('overview', models.TextField(help_text='Full HTML overview content (CKEditor)')),
                ('pain_points', models.JSONField(blank=True, default=list, help_text='List of {title, description, icon} objects representing pain points')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of {title, description, icon, metric} objects')),
                ('workflow_title', models.CharField(blank=True, max_length=200)),
                ('workflow_description', models.TextField(blank=True)),
                ('cta_title', models.CharField(default='Ready to Get Started?', max_length=200)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_primary_text', models.CharField(default='Request a Demo', max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Request Quotation', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/contact/quote/', max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('product_category', models.ForeignKey(blank=True, help_text='Link to product category for auto-product display', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('related_solutions', models.ManyToManyField(blank=True, to='solutions.solution')),
                ('solution_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='solutions.solutioncategory')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='cases/logos/')),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('challenge', models.TextField()),
                ('solution_applied', models.TextField()),
                ('results', models.JSONField(default=list, help_text='List of {metric, value, unit} result objects')),
                ('testimonial', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=200)),
                ('testimonial_title', models.CharField(blank=True, max_length=200)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cases', to='solutions.solution')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchitectureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('block_type', models.CharField(choices=[('diagram', 'Architecture Diagram'), ('image', 'Image Block'), ('html', 'HTML/Text Block')], default='image', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions/architecture/')),
                ('html_content', models.TextField(blank=True, help_text='Custom HTML for complex diagrams')),
                ('layers', models.JSONField(blank=True, default=list, help_text='List of {name, color, nodes: [{label, icon, description}]} for architecture layers')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_blocks', to='solutions.solution')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SolutionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this product in the solution page')),
                ('role_description', models.CharField(blank=True, help_text='How this product is used in the solution', max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.solution')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('solution', 'product')},
            },
        ),
        migrations.AddField(
            model_name='solution',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='solutions', through='solutions.SolutionProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions/workflow/')),
                ('highlight_color', models.CharField(default='blue', help_text='Tailwind color name', max_length=20)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='solutions.solution')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['status', 'is_featured'], name='solutions_s_status_e2606a_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['solution_category', 'status'], name='solutions_s_solutio_29a9d1_idx'),
        ),
    ]
