# Generated by Django 5.2.12 on 2026-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architectureblock',
            options={'ordering': ['sort_order'], 'verbose_name': 'Architecture Block'},
        ),
        migrations.AlterModelOptions(
            name='customercase',
            options={'ordering': ['-published_at'], 'verbose_name': 'Customer Case', 'verbose_name_plural': 'Customer Cases'},
        ),
        migrations.AlterModelOptions(
            name='workflowstep',
            options={'ordering': ['step_number'], 'verbose_name': 'Workflow Step'},
        ),
        migrations.RemoveField(
            model_name='architectureblock',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='architectureblock',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='architectureblock',
            name='layers',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='cta_primary_url',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='cta_secondary_url',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='related_solutions',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='highlight_color',
        ),
        migrations.AlterField(
            model_name='customercase',
            name='challenge',
            field=models.TextField(help_text='Thách thức / vấn đề ban đầu'),
        ),
        migrations.AlterField(
            model_name='customercase',
            name='country',
            field=models.CharField(default='Việt Nam', max_length=100),
        ),
        migrations.AlterField(
            model_name='customercase',
            name='results',
            field=models.JSONField(default=list, help_text='Ví dụ: [{"metric": "Tiết kiệm điện", "value": "35", "unit": "%"}]'),
        ),
        migrations.AlterField(
            model_name='customercase',
            name='solution_applied',
            field=models.TextField(help_text='Giải pháp đã áp dụng'),
        ),
        migrations.AlterField(
            model_name='customercase',
            name='testimonial_title',
            field=models.CharField(blank=True, help_text='Chức danh người trích dẫn', max_length=200),
        ),
        migrations.AlterField(
            model_name='solution',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Ví dụ: [{"title": "Tiết kiệm 30% nước", "metric": "30%", "icon": "droplet"}]'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='URL nhúng YouTube / Vimeo'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='overview',
            field=models.TextField(help_text='Nội dung HTML đầy đủ (dùng CKEditor)'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='pain_points',
            field=models.JSONField(blank=True, default=list, help_text='Ví dụ: [{"title": "Khó giám sát từ xa", "icon": "eye-off"}]'),
        ),
        migrations.AlterField(
            model_name='solutioncategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text='CSS icon class', max_length=100),
        ),
        migrations.AlterField(
            model_name='solutionproduct',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Hiển thị nổi bật trên trang solution'),
        ),
        migrations.AlterField(
            model_name='solutionproduct',
            name='role_description',
            field=models.CharField(blank=True, help_text='Mô tả vai trò sản phẩm trong giải pháp', max_length=300),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='icon_class',
            field=models.CharField(blank=True, help_text='CSS icon class', max_length=100),
        ),
    ]
