# Generated by Django 5.2.12 on 2026-04-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_architectureblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='cta_primary_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solution',
            name='cta_primary_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solution',
            name='cta_secondary_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solution',
            name='cta_secondary_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solution',
            name='cta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
